services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=US/Pacific
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ./config:/config
      - /mnt/storage:/storage
      - ./fonts:/usr/local/share/fonts/custom
    ports:
      - 8096:8096
    restart: always

networks:
  default:
    name: web
    external: true
